# Generated by Django 5.1.7 on 2025-04-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_updated_at_comment_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Blog-Categories'},
        ),
    ]
