# Generated by Django 4.2.14 on 2024-10-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client_slide',
            new_name='Client',
        ),
    ]
