# Generated by Django 4.2.14 on 2024-10-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='media/projects/slider_images')),
                ('caption', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_slide',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_finished',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='SliderImages',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Portfolio.project'),
        ),
    ]
