# Generated by Django 4.2.14 on 2025-02-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_portfoliocategory_portfolioitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_start', models.DateField()),
                ('project_finished', models.DateField()),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('project_url', models.URLField()),
                ('project_logo', models.ImageField(upload_to='media/projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='media/projects/slider_images')),
                ('caption', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Portfolio.project')),
            ],
        ),
    ]
