# Generated by Django 4.2.14 on 2025-04-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_project_projectimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioCategory',
            new_name='Category',
        ),
    ]
