# Generated by Django 4.2.14 on 2025-04-23 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_rename_portfoliocategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='slider_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_logo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Portfolio.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed HTML content'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, help_text='Date of project delivery', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(help_text='Main technologies used', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/projects/gallery/'),
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
